name: ktlint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - .github/workflows/basics.yml
      - 'src/**/*.kt'
      - '**.kts'
      
  workflow_dispatch:

jobs:
  ktlint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: |
            curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
        - name: run ktlint
          run: |
            ktlint --reporter=checkstyle,output=build/ktlint-report.xml
          continue-on-error: true
        - uses: yutailang0119/action-ktlint@v3
          with:
            report-path: build/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
          continue-on-error: false # If annotations contain error of severity, action-ktlint exit 1.
          
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!      
       
      - name: List of current folders
        run: ls -la

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
